services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meticulous-backend
    ports:
      - 8080:8080
    expose:
      - 8080
    user: "${USER_ID:-root}:${GROUP_ID:-0}"
    command: ["/bin/bash", "/app/start_container.sh"]
    environment:
      - BACKEND=emulation
      - EMULATION_SPEED=100
      - CONFIG_PATH=/app/config
      - LOG_PATH=/app/logs
      - PROFILE_PATH=/app/profiles
      - HISTORY_PATH=/app/history
      - DEBUG_HISTORY_PATH=/app/history/debug
      - UPDATE_PATH=/tmp/firmware
      - ZEROCONF_OVERWRITE=192.168.2.11/24,Mimoja-Datenschleuder
      - PORT=8080
      - DEFAULT_IMAGES=/app/images/default
      - IMAGES_PATH=/app/images/profile-images
      - DEFAULT_PROFILES=/app/default_profiles
      - REPORTS_DIR=/app/reports
    volumes:
      - .:/app
      - ./config:/app/config
      - ./logs:/app/logs
      - ./profiles:/app/profiles
      - ./history:/app/history
      - ./images:/app/images
      - ./default_profiles:/app/default_profiles
      - ./reports:/app/reports
      - /tmp/met_image-build-channel:/opt/image-build-channel
